name: Config Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.10.2/sing-box_1.10.2_linux_amd64.deb"
      run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb
    - name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml
    - name: Download and Convert AdGuard Files
      run: |
        # 定义要下载的文件列表
        declare -A FILES=(
          ["AdGuardSDNSFilter"]="https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
          ["AdGuardMobileFilter"]="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/specific_app.txt"
          # 添加更多文件...
        )

        # 下载和转换每个文件
        for name in "${!FILES[@]}"; do
          URL="${FILES[$name]}"
          OUTPUT_FILE="./Sing-Box/Rule/${name}.txt"
          
          echo "Downloading $name from $URL"
          curl -L "$URL" -o "$OUTPUT_FILE"
          
          if [ -f "$OUTPUT_FILE" ]; then
            echo "Converting $name to SRS format"
            sing-box rule-set convert --type adguard --output "./Sing-Box/Rule/${name}.srs" "$OUTPUT_FILE"
          else
            echo "Download failed for $name"
            exit 1
          fi
        done
    - name: Compile Custom JSON files to SRS
      run: |
        # 检查Custom目录是否存在
        if [ -d "./Sing-Box/Custom" ]; then
          # 遍历所有json文件
          for json_file in ./Sing-Box/Custom/*.json; do
            if [ -f "$json_file" ]; then
              filename=$(basename "$json_file" .json)
              echo "Compiling $filename.json to SRS format"
              sing-box rule-set compile --output "./Sing-Box/Custom/${filename}.srs" "$json_file"
            fi
          done
        else
          echo "Custom directory not found"
        fi
    - name: Run script
      run: python ../main.py
      working-directory: ./Sing-Box
    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./Sing-Box/Rule/*.json
        git add ./Sing-Box/Rule/*.srs
        git add ./Sing-Box/Rule/*.txt

        # 检查是否有文件被修改
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update rules"
          git push
        fi
